import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import Layout, {siteTitle} from '../components/Layout';
import axios from 'axios';

export default function Home({ posts }) {


  return (
    <Layout home>

    <div className={styles.container}>
      <Head>
        <title>{siteTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
 
          {
            posts.map((post, index) => (
              <div key={index}>
                <Link href="posts/[id]" as={`posts/2`}>
                <a>{post.title}</a> 
                </Link>
              </div> 
            ))
          }

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    </Layout>
  )
}


export const getStaticProps = async () => {
  
  const res = await axios.get('https://jsonplaceholder.typicode.com/posts?_limit=6');
  const posts = await res.data
  return {
    props : {
      posts
    }
  }
}